/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiInfoGetApi } from "../../funcs/apiInfoGetApi.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$apiInfoGetApi: ToolDefinition = {
  name: "api-info-get-api",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await apiInfoGetApi(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
