/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { applicationDeleteApiV1ApplicationsBulk } from "../../funcs/applicationDeleteApiV1ApplicationsBulk.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.ApplicationBulkResource$inboundSchema.optional(),
};

export const tool$applicationDeleteApiV1ApplicationsBulk: ToolDefinition<
  typeof args
> = {
  name: "application-delete-api-v1-applications-bulk",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await applicationDeleteApiV1ApplicationsBulk(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
