/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { applicationDeleteApiV1ApplicationsId } from "../../funcs/applicationDeleteApiV1ApplicationsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiV1ApplicationsIdRequest$inboundSchema,
};

export const tool$applicationDeleteApiV1ApplicationsId: ToolDefinition<
  typeof args
> = {
  name: "application-delete-api-v1-applications-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await applicationDeleteApiV1ApplicationsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
