/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { applicationPostApiV1ApplicationsActionName } from "../../funcs/applicationPostApiV1ApplicationsActionName.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1ApplicationsActionNameRequest$inboundSchema,
};

export const tool$applicationPostApiV1ApplicationsActionName: ToolDefinition<
  typeof args
> = {
  name: "application-post-api-v1-applications-action-name",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await applicationPostApiV1ApplicationsActionName(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
