/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { applicationGetApiV1ApplicationsSchema } from "../../funcs/applicationGetApiV1ApplicationsSchema.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$applicationGetApiV1ApplicationsSchema: ToolDefinition = {
  name: "application-get-api-v1-applications-schema",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await applicationGetApiV1ApplicationsSchema(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
