/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { appProfileGetApiV1AppprofileSchema } from "../../funcs/appProfileGetApiV1AppprofileSchema.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$appProfileGetApiV1AppprofileSchema: ToolDefinition = {
  name: "app-profile-get-api-v1-appprofile-schema",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await appProfileGetApiV1AppprofileSchema(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
