/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { appProfilePostApiV1Appprofile } from "../../funcs/appProfilePostApiV1Appprofile.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.AppProfileResource$inboundSchema.optional(),
};

export const tool$appProfilePostApiV1Appprofile: ToolDefinition<typeof args> = {
  name: "app-profile-post-api-v1-appprofile",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await appProfilePostApiV1Appprofile(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
