/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { appProfileGetApiV1AppprofileId } from "../../funcs/appProfileGetApiV1AppprofileId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1AppprofileIdRequest$inboundSchema,
};

export const tool$appProfileGetApiV1AppprofileId: ToolDefinition<typeof args> =
  {
    name: "app-profile-get-api-v1-appprofile-id",
    description: ``,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await appProfileGetApiV1AppprofileId(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
