/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { backupDeleteApiV1SystemBackupId } from "../../funcs/backupDeleteApiV1SystemBackupId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiV1SystemBackupIdRequest$inboundSchema,
};

export const tool$backupDeleteApiV1SystemBackupId: ToolDefinition<typeof args> =
  {
    name: "backup-delete-api-v1-system-backup-id",
    description: ``,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await backupDeleteApiV1SystemBackupId(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(void 0, apiCall);
    },
  };
