/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { backupPostApiV1SystemBackupRestoreUpload } from "../../funcs/backupPostApiV1SystemBackupRestoreUpload.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$backupPostApiV1SystemBackupRestoreUpload: ToolDefinition = {
  name: "backup-post-api-v1-system-backup-restore-upload",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await backupPostApiV1SystemBackupRestoreUpload(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
