/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { backupPostApiV1SystemBackupRestoreId } from "../../funcs/backupPostApiV1SystemBackupRestoreId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1SystemBackupRestoreIdRequest$inboundSchema,
};

export const tool$backupPostApiV1SystemBackupRestoreId: ToolDefinition<
  typeof args
> = {
  name: "backup-post-api-v1-system-backup-restore-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await backupPostApiV1SystemBackupRestoreId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
