/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { backupGetApiV1SystemBackup } from "../../funcs/backupGetApiV1SystemBackup.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$backupGetApiV1SystemBackup: ToolDefinition = {
  name: "backup-get-api-v1-system-backup",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await backupGetApiV1SystemBackup(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
