/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { commandGetApiV1Command } from "../../funcs/commandGetApiV1Command.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$commandGetApiV1Command: ToolDefinition = {
  name: "command-get-api-v1-command",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await commandGetApiV1Command(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
