/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { commandPostApiV1Command } from "../../funcs/commandPostApiV1Command.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.CommandResourceInput$inboundSchema.optional(),
};

export const tool$commandPostApiV1Command: ToolDefinition<typeof args> = {
  name: "command-post-api-v1-command",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await commandPostApiV1Command(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
