/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { commandDeleteApiV1CommandId } from "../../funcs/commandDeleteApiV1CommandId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiV1CommandIdRequest$inboundSchema,
};

export const tool$commandDeleteApiV1CommandId: ToolDefinition<typeof args> = {
  name: "command-delete-api-v1-command-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await commandDeleteApiV1CommandId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
