/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customFilterDeleteApiV1CustomfilterId } from "../../funcs/customFilterDeleteApiV1CustomfilterId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiV1CustomfilterIdRequest$inboundSchema,
};

export const tool$customFilterDeleteApiV1CustomfilterId: ToolDefinition<
  typeof args
> = {
  name: "custom-filter-delete-api-v1-customfilter-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customFilterDeleteApiV1CustomfilterId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
