/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customFilterGetApiV1Customfilter } from "../../funcs/customFilterGetApiV1Customfilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$customFilterGetApiV1Customfilter: ToolDefinition = {
  name: "custom-filter-get-api-v1-customfilter",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await customFilterGetApiV1Customfilter(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
