/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { developmentConfigPutApiV1ConfigDevelopmentId } from "../../funcs/developmentConfigPutApiV1ConfigDevelopmentId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PutApiV1ConfigDevelopmentIdRequest$inboundSchema,
};

export const tool$developmentConfigPutApiV1ConfigDevelopmentId: ToolDefinition<
  typeof args
> = {
  name: "development-config-put-api-v1-config-development-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] =
      await developmentConfigPutApiV1ConfigDevelopmentId(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
