/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { developmentConfigGetApiV1ConfigDevelopment } from "../../funcs/developmentConfigGetApiV1ConfigDevelopment.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$developmentConfigGetApiV1ConfigDevelopment: ToolDefinition = {
  name: "development-config-get-api-v1-config-development",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await developmentConfigGetApiV1ConfigDevelopment(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
