/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { downloadClientPutApiV1DownloadclientBulk } from "../../funcs/downloadClientPutApiV1DownloadclientBulk.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.DownloadClientBulkResource$inboundSchema.optional(),
};

export const tool$downloadClientPutApiV1DownloadclientBulk: ToolDefinition<
  typeof args
> = {
  name: "download-client-put-api-v1-downloadclient-bulk",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await downloadClientPutApiV1DownloadclientBulk(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
