/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { downloadClientPostApiV1Downloadclient } from "../../funcs/downloadClientPostApiV1Downloadclient.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1DownloadclientRequest$inboundSchema,
};

export const tool$downloadClientPostApiV1Downloadclient: ToolDefinition<
  typeof args
> = {
  name: "download-client-post-api-v1-downloadclient",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await downloadClientPostApiV1Downloadclient(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
