/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { downloadClientDeleteApiV1DownloadclientId } from "../../funcs/downloadClientDeleteApiV1DownloadclientId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiV1DownloadclientIdRequest$inboundSchema,
};

export const tool$downloadClientDeleteApiV1DownloadclientId: ToolDefinition<
  typeof args
> = {
  name: "download-client-delete-api-v1-downloadclient-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await downloadClientDeleteApiV1DownloadclientId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
