/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { downloadClientDeleteApiV1DownloadclientBulk } from "../../funcs/downloadClientDeleteApiV1DownloadclientBulk.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.DownloadClientBulkResource$inboundSchema.optional(),
};

export const tool$downloadClientDeleteApiV1DownloadclientBulk: ToolDefinition<
  typeof args
> = {
  name: "download-client-delete-api-v1-downloadclient-bulk",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await downloadClientDeleteApiV1DownloadclientBulk(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
