/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { downloadClientConfigGetApiV1ConfigDownloadclientId } from "../../funcs/downloadClientConfigGetApiV1ConfigDownloadclientId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1ConfigDownloadclientIdRequest$inboundSchema,
};

export const tool$downloadClientConfigGetApiV1ConfigDownloadclientId:
  ToolDefinition<typeof args> = {
    name: "download-client-config-get-api-v1-config-downloadclient-id",
    description: ``,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await downloadClientConfigGetApiV1ConfigDownloadclientId(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
