/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { downloadClientPostApiV1DownloadclientTestall } from "../../funcs/downloadClientPostApiV1DownloadclientTestall.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$downloadClientPostApiV1DownloadclientTestall: ToolDefinition =
  {
    name: "download-client-post-api-v1-downloadclient-testall",
    description: ``,
    tool: async (client, ctx) => {
      const [result, apiCall] =
        await downloadClientPostApiV1DownloadclientTestall(
          client,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(void 0, apiCall);
    },
  };
