/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { downloadClientGetApiV1DownloadclientId } from "../../funcs/downloadClientGetApiV1DownloadclientId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1DownloadclientIdRequest$inboundSchema,
};

export const tool$downloadClientGetApiV1DownloadclientId: ToolDefinition<
  typeof args
> = {
  name: "download-client-get-api-v1-downloadclient-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await downloadClientGetApiV1DownloadclientId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
