/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { downloadClientPostApiV1DownloadclientTest } from "../../funcs/downloadClientPostApiV1DownloadclientTest.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1DownloadclientTestRequest$inboundSchema,
};

export const tool$downloadClientPostApiV1DownloadclientTest: ToolDefinition<
  typeof args
> = {
  name: "download-client-post-api-v1-downloadclient-test",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await downloadClientPostApiV1DownloadclientTest(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
