/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { downloadClientConfigGetApiV1ConfigDownloadclient } from "../../funcs/downloadClientConfigGetApiV1ConfigDownloadclient.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$downloadClientConfigGetApiV1ConfigDownloadclient:
  ToolDefinition = {
    name: "download-client-config-get-api-v1-config-downloadclient",
    description: ``,
    tool: async (client, ctx) => {
      const [result, apiCall] =
        await downloadClientConfigGetApiV1ConfigDownloadclient(
          client,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
