/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { downloadClientGetApiV1Downloadclient } from "../../funcs/downloadClientGetApiV1Downloadclient.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$downloadClientGetApiV1Downloadclient: ToolDefinition = {
  name: "download-client-get-api-v1-downloadclient",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await downloadClientGetApiV1Downloadclient(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
