/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fileSystemGetApiV1FilesystemType } from "../../funcs/fileSystemGetApiV1FilesystemType.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1FilesystemTypeRequest$inboundSchema,
};

export const tool$fileSystemGetApiV1FilesystemType: ToolDefinition<
  typeof args
> = {
  name: "file-system-get-api-v1-filesystem-type",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await fileSystemGetApiV1FilesystemType(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
