/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { historyGetApiV1HistoryIndexer } from "../../funcs/historyGetApiV1HistoryIndexer.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1HistoryIndexerRequest$inboundSchema,
};

export const tool$historyGetApiV1HistoryIndexer: ToolDefinition<typeof args> = {
  name: "history-get-api-v1-history-indexer",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await historyGetApiV1HistoryIndexer(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
