/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { historyGetApiV1HistorySince } from "../../funcs/historyGetApiV1HistorySince.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1HistorySinceRequest$inboundSchema,
};

export const tool$historyGetApiV1HistorySince: ToolDefinition<typeof args> = {
  name: "history-get-api-v1-history-since",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await historyGetApiV1HistorySince(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
