/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { hostConfigGetApiV1ConfigHost } from "../../funcs/hostConfigGetApiV1ConfigHost.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$hostConfigGetApiV1ConfigHost: ToolDefinition = {
  name: "host-config-get-api-v1-config-host",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await hostConfigGetApiV1ConfigHost(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
