/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indexerProxyPostApiV1Indexerproxy } from "../../funcs/indexerProxyPostApiV1Indexerproxy.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1IndexerproxyRequest$inboundSchema,
};

export const tool$indexerProxyPostApiV1Indexerproxy: ToolDefinition<
  typeof args
> = {
  name: "indexer-proxy-post-api-v1-indexerproxy",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await indexerProxyPostApiV1Indexerproxy(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
