/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indexerProxyGetApiV1Indexerproxy } from "../../funcs/indexerProxyGetApiV1Indexerproxy.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$indexerProxyGetApiV1Indexerproxy: ToolDefinition = {
  name: "indexer-proxy-get-api-v1-indexerproxy",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await indexerProxyGetApiV1Indexerproxy(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
