/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indexerStatusGetApiV1Indexerstatus } from "../../funcs/indexerStatusGetApiV1Indexerstatus.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$indexerStatusGetApiV1Indexerstatus: ToolDefinition = {
  name: "indexer-status-get-api-v1-indexerstatus",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await indexerStatusGetApiV1Indexerstatus(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
