/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indexerGetApiV1IndexerSchema } from "../../funcs/indexerGetApiV1IndexerSchema.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$indexerGetApiV1IndexerSchema: ToolDefinition = {
  name: "indexer-get-api-v1-indexer-schema",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await indexerGetApiV1IndexerSchema(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
