/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indexerStatsGetApiV1Indexerstats } from "../../funcs/indexerStatsGetApiV1Indexerstats.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1IndexerstatsRequest$inboundSchema,
};

export const tool$indexerStatsGetApiV1Indexerstats: ToolDefinition<
  typeof args
> = {
  name: "indexer-stats-get-api-v1-indexerstats",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await indexerStatsGetApiV1Indexerstats(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
