/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indexerDefaultCategoriesGetApiV1IndexerCategories } from "../../funcs/indexerDefaultCategoriesGetApiV1IndexerCategories.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$indexerDefaultCategoriesGetApiV1IndexerCategories:
  ToolDefinition = {
    name: "indexer-default-categories-get-api-v1-indexer-categories",
    description: ``,
    tool: async (client, ctx) => {
      const [result, apiCall] =
        await indexerDefaultCategoriesGetApiV1IndexerCategories(
          client,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
