/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indexerProxyPostApiV1IndexerproxyTestall } from "../../funcs/indexerProxyPostApiV1IndexerproxyTestall.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$indexerProxyPostApiV1IndexerproxyTestall: ToolDefinition = {
  name: "indexer-proxy-post-api-v1-indexerproxy-testall",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await indexerProxyPostApiV1IndexerproxyTestall(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
