/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indexerProxyGetApiV1IndexerproxyId } from "../../funcs/indexerProxyGetApiV1IndexerproxyId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1IndexerproxyIdRequest$inboundSchema,
};

export const tool$indexerProxyGetApiV1IndexerproxyId: ToolDefinition<
  typeof args
> = {
  name: "indexer-proxy-get-api-v1-indexerproxy-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await indexerProxyGetApiV1IndexerproxyId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
