/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indexerProxyDeleteApiV1IndexerproxyId } from "../../funcs/indexerProxyDeleteApiV1IndexerproxyId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiV1IndexerproxyIdRequest$inboundSchema,
};

export const tool$indexerProxyDeleteApiV1IndexerproxyId: ToolDefinition<
  typeof args
> = {
  name: "indexer-proxy-delete-api-v1-indexerproxy-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await indexerProxyDeleteApiV1IndexerproxyId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
