/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indexerProxyPostApiV1IndexerproxyActionName } from "../../funcs/indexerProxyPostApiV1IndexerproxyActionName.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1IndexerproxyActionNameRequest$inboundSchema,
};

export const tool$indexerProxyPostApiV1IndexerproxyActionName: ToolDefinition<
  typeof args
> = {
  name: "indexer-proxy-post-api-v1-indexerproxy-action-name",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await indexerProxyPostApiV1IndexerproxyActionName(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
