/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indexerPutApiV1IndexerBulk } from "../../funcs/indexerPutApiV1IndexerBulk.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.IndexerBulkResource$inboundSchema.optional(),
};

export const tool$indexerPutApiV1IndexerBulk: ToolDefinition<typeof args> = {
  name: "indexer-put-api-v1-indexer-bulk",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await indexerPutApiV1IndexerBulk(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
