/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indexerPostApiV1IndexerTest } from "../../funcs/indexerPostApiV1IndexerTest.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1IndexerTestRequest$inboundSchema,
};

export const tool$indexerPostApiV1IndexerTest: ToolDefinition<typeof args> = {
  name: "indexer-post-api-v1-indexer-test",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await indexerPostApiV1IndexerTest(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
