/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { localizationGetApiV1Localization } from "../../funcs/localizationGetApiV1Localization.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$localizationGetApiV1Localization: ToolDefinition = {
  name: "localization-get-api-v1-localization",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await localizationGetApiV1Localization(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
