/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { logFileGetApiV1LogFileFilename } from "../../funcs/logFileGetApiV1LogFileFilename.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1LogFileFilenameRequest$inboundSchema,
};

export const tool$logFileGetApiV1LogFileFilename: ToolDefinition<typeof args> =
  {
    name: "log-file-get-api-v1-log-file-filename",
    description: ``,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await logFileGetApiV1LogFileFilename(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
