/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { logFileGetApiV1LogFile } from "../../funcs/logFileGetApiV1LogFile.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$logFileGetApiV1LogFile: ToolDefinition = {
  name: "log-file-get-api-v1-log-file",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await logFileGetApiV1LogFile(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
