/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { newznabGetIdApi } from "../../funcs/newznabGetIdApi.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetIdApiRequest$inboundSchema,
};

export const tool$newznabGetIdApi: ToolDefinition<typeof args> = {
  name: "newznab-get-id-api",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await newznabGetIdApi(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
