/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { newznabGetApiV1IndexerIdNewznab } from "../../funcs/newznabGetApiV1IndexerIdNewznab.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1IndexerIdNewznabRequest$inboundSchema,
};

export const tool$newznabGetApiV1IndexerIdNewznab: ToolDefinition<typeof args> =
  {
    name: "newznab-get-api-v1-indexer-id-newznab",
    description: ``,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await newznabGetApiV1IndexerIdNewznab(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(void 0, apiCall);
    },
  };
