/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { notificationGetApiV1NotificationId } from "../../funcs/notificationGetApiV1NotificationId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1NotificationIdRequest$inboundSchema,
};

export const tool$notificationGetApiV1NotificationId: ToolDefinition<
  typeof args
> = {
  name: "notification-get-api-v1-notification-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await notificationGetApiV1NotificationId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
