/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { notificationPostApiV1NotificationActionName } from "../../funcs/notificationPostApiV1NotificationActionName.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1NotificationActionNameRequest$inboundSchema,
};

export const tool$notificationPostApiV1NotificationActionName: ToolDefinition<
  typeof args
> = {
  name: "notification-post-api-v1-notification-action-name",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await notificationPostApiV1NotificationActionName(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
