/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { notificationPostApiV1NotificationTestall } from "../../funcs/notificationPostApiV1NotificationTestall.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$notificationPostApiV1NotificationTestall: ToolDefinition = {
  name: "notification-post-api-v1-notification-testall",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await notificationPostApiV1NotificationTestall(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
