/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { notificationPostApiV1Notification } from "../../funcs/notificationPostApiV1Notification.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1NotificationRequest$inboundSchema,
};

export const tool$notificationPostApiV1Notification: ToolDefinition<
  typeof args
> = {
  name: "notification-post-api-v1-notification",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await notificationPostApiV1Notification(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
