/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pingHeadPing } from "../../funcs/pingHeadPing.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$pingHeadPing: ToolDefinition = {
  name: "ping-head-ping",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await pingHeadPing(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
