/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { searchPostApiV1Search } from "../../funcs/searchPostApiV1Search.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.ReleaseResourceInput$inboundSchema.optional(),
};

export const tool$searchPostApiV1Search: ToolDefinition<typeof args> = {
  name: "search-post-api-v1-search",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await searchPostApiV1Search(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
