/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { searchPostApiV1SearchBulk } from "../../funcs/searchPostApiV1SearchBulk.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: z.array(models.ReleaseResourceInput$inboundSchema).optional(),
};

export const tool$searchPostApiV1SearchBulk: ToolDefinition<typeof args> = {
  name: "search-post-api-v1-search-bulk",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await searchPostApiV1SearchBulk(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
