/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { staticResourceGetLogin } from "../../funcs/staticResourceGetLogin.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$staticResourceGetLogin: ToolDefinition = {
  name: "static-resource-get-login",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await staticResourceGetLogin(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
