/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { systemGetApiV1SystemStatus } from "../../funcs/systemGetApiV1SystemStatus.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$systemGetApiV1SystemStatus: ToolDefinition = {
  name: "system-get-api-v1-system-status",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await systemGetApiV1SystemStatus(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
