/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { systemPostApiV1SystemShutdown } from "../../funcs/systemPostApiV1SystemShutdown.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$systemPostApiV1SystemShutdown: ToolDefinition = {
  name: "system-post-api-v1-system-shutdown",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await systemPostApiV1SystemShutdown(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
