/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tagDeleteApiV1TagId } from "../../funcs/tagDeleteApiV1TagId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiV1TagIdRequest$inboundSchema,
};

export const tool$tagDeleteApiV1TagId: ToolDefinition<typeof args> = {
  name: "tag-delete-api-v1-tag-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tagDeleteApiV1TagId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
