/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tagDetailsGetApiV1TagDetailId } from "../../funcs/tagDetailsGetApiV1TagDetailId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1TagDetailIdRequest$inboundSchema,
};

export const tool$tagDetailsGetApiV1TagDetailId: ToolDefinition<typeof args> = {
  name: "tag-details-get-api-v1-tag-detail-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tagDetailsGetApiV1TagDetailId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
