/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tagPostApiV1Tag } from "../../funcs/tagPostApiV1Tag.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.TagResource$inboundSchema.optional(),
};

export const tool$tagPostApiV1Tag: ToolDefinition<typeof args> = {
  name: "tag-post-api-v1-tag",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tagPostApiV1Tag(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
