/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taskGetApiV1SystemTaskId } from "../../funcs/taskGetApiV1SystemTaskId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1SystemTaskIdRequest$inboundSchema,
};

export const tool$taskGetApiV1SystemTaskId: ToolDefinition<typeof args> = {
  name: "task-get-api-v1-system-task-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await taskGetApiV1SystemTaskId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
