/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { uiConfigPutApiV1ConfigUiId } from "../../funcs/uiConfigPutApiV1ConfigUiId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PutApiV1ConfigUiIdRequest$inboundSchema,
};

export const tool$uiConfigPutApiV1ConfigUiId: ToolDefinition<typeof args> = {
  name: "ui-config-put-api-v1-config-ui-id",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await uiConfigPutApiV1ConfigUiId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
