/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { uiConfigGetApiV1ConfigUi } from "../../funcs/uiConfigGetApiV1ConfigUi.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$uiConfigGetApiV1ConfigUi: ToolDefinition = {
  name: "ui-config-get-api-v1-config-ui",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await uiConfigGetApiV1ConfigUi(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
