/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { updateGetApiV1Update } from "../../funcs/updateGetApiV1Update.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$updateGetApiV1Update: ToolDefinition = {
  name: "update-get-api-v1-update",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await updateGetApiV1Update(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
