/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { updateLogFileGetApiV1LogFileUpdate } from "../../funcs/updateLogFileGetApiV1LogFileUpdate.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$updateLogFileGetApiV1LogFileUpdate: ToolDefinition = {
  name: "update-log-file-get-api-v1-log-file-update",
  description: ``,
  tool: async (client, ctx) => {
    const [result, apiCall] = await updateLogFileGetApiV1LogFileUpdate(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
