/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { updateLogFileGetApiV1LogFileUpdateFilename } from "../../funcs/updateLogFileGetApiV1LogFileUpdateFilename.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1LogFileUpdateFilenameRequest$inboundSchema,
};

export const tool$updateLogFileGetApiV1LogFileUpdateFilename: ToolDefinition<
  typeof args
> = {
  name: "update-log-file-get-api-v1-log-file-update-filename",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await updateLogFileGetApiV1LogFileUpdateFilename(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
