/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationGetLogout } from "../funcs/authenticationGetLogout.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class Authentication extends ClientSDK {
  async getLogout(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(authenticationGetLogout(
      this,
      options,
    ));
  }
}
