/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { backupDeleteApiV1SystemBackupId } from "../funcs/backupDeleteApiV1SystemBackupId.js";
import { backupGetApiV1SystemBackup } from "../funcs/backupGetApiV1SystemBackup.js";
import { backupPostApiV1SystemBackupRestoreId } from "../funcs/backupPostApiV1SystemBackupRestoreId.js";
import { backupPostApiV1SystemBackupRestoreUpload } from "../funcs/backupPostApiV1SystemBackupRestoreUpload.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Backup extends ClientSDK {
  async getApiV1SystemBackup(
    options?: RequestOptions,
  ): Promise<Array<models.BackupResource>> {
    return unwrapAsync(backupGetApiV1SystemBackup(
      this,
      options,
    ));
  }

  async deleteApiV1SystemBackupId(
    request: operations.DeleteApiV1SystemBackupIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(backupDeleteApiV1SystemBackupId(
      this,
      request,
      options,
    ));
  }

  async postApiV1SystemBackupRestoreId(
    request: operations.PostApiV1SystemBackupRestoreIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(backupPostApiV1SystemBackupRestoreId(
      this,
      request,
      options,
    ));
  }

  async postApiV1SystemBackupRestoreUpload(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(backupPostApiV1SystemBackupRestoreUpload(
      this,
      options,
    ));
  }
}
