/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { downloadClientConfigGetApiV1ConfigDownloadclient } from "../funcs/downloadClientConfigGetApiV1ConfigDownloadclient.js";
import { downloadClientConfigGetApiV1ConfigDownloadclientId } from "../funcs/downloadClientConfigGetApiV1ConfigDownloadclientId.js";
import { downloadClientConfigPutApiV1ConfigDownloadclientId } from "../funcs/downloadClientConfigPutApiV1ConfigDownloadclientId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class DownloadClientConfig extends ClientSDK {
  async getApiV1ConfigDownloadclientId(
    request: operations.GetApiV1ConfigDownloadclientIdRequest,
    options?: RequestOptions,
  ): Promise<models.DownloadClientConfigResource> {
    return unwrapAsync(downloadClientConfigGetApiV1ConfigDownloadclientId(
      this,
      request,
      options,
    ));
  }

  async putApiV1ConfigDownloadclientId(
    request: operations.PutApiV1ConfigDownloadclientIdRequest,
    options?: RequestOptions,
  ): Promise<models.DownloadClientConfigResource> {
    return unwrapAsync(downloadClientConfigPutApiV1ConfigDownloadclientId(
      this,
      request,
      options,
    ));
  }

  async getApiV1ConfigDownloadclient(
    options?: RequestOptions,
  ): Promise<models.DownloadClientConfigResource> {
    return unwrapAsync(downloadClientConfigGetApiV1ConfigDownloadclient(
      this,
      options,
    ));
  }
}
