/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fileSystemGetApiV1Filesystem } from "../funcs/fileSystemGetApiV1Filesystem.js";
import { fileSystemGetApiV1FilesystemType } from "../funcs/fileSystemGetApiV1FilesystemType.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class FileSystem extends ClientSDK {
  async getApiV1Filesystem(
    request: operations.GetApiV1FilesystemRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(fileSystemGetApiV1Filesystem(
      this,
      request,
      options,
    ));
  }

  async getApiV1FilesystemType(
    request: operations.GetApiV1FilesystemTypeRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(fileSystemGetApiV1FilesystemType(
      this,
      request,
      options,
    ));
  }
}
