/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { healthGetApiV1Health } from "../funcs/healthGetApiV1Health.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Health extends ClientSDK {
  async getApiV1Health(
    options?: RequestOptions,
  ): Promise<Array<models.HealthResource>> {
    return unwrapAsync(healthGetApiV1Health(
      this,
      options,
    ));
  }
}
