/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { historyGetApiV1History } from "../funcs/historyGetApiV1History.js";
import { historyGetApiV1HistoryIndexer } from "../funcs/historyGetApiV1HistoryIndexer.js";
import { historyGetApiV1HistorySince } from "../funcs/historyGetApiV1HistorySince.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class History extends ClientSDK {
  async getApiV1History(
    request: operations.GetApiV1HistoryRequest,
    options?: RequestOptions,
  ): Promise<models.HistoryResourcePagingResource> {
    return unwrapAsync(historyGetApiV1History(
      this,
      request,
      options,
    ));
  }

  async getApiV1HistorySince(
    request: operations.GetApiV1HistorySinceRequest,
    options?: RequestOptions,
  ): Promise<Array<models.HistoryResource>> {
    return unwrapAsync(historyGetApiV1HistorySince(
      this,
      request,
      options,
    ));
  }

  async getApiV1HistoryIndexer(
    request: operations.GetApiV1HistoryIndexerRequest,
    options?: RequestOptions,
  ): Promise<Array<models.HistoryResource>> {
    return unwrapAsync(historyGetApiV1HistoryIndexer(
      this,
      request,
      options,
    ));
  }
}
