/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { hostConfigGetApiV1ConfigHost } from "../funcs/hostConfigGetApiV1ConfigHost.js";
import { hostConfigGetApiV1ConfigHostId } from "../funcs/hostConfigGetApiV1ConfigHostId.js";
import { hostConfigPutApiV1ConfigHostId } from "../funcs/hostConfigPutApiV1ConfigHostId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class HostConfig extends ClientSDK {
  async getApiV1ConfigHostId(
    request: operations.GetApiV1ConfigHostIdRequest,
    options?: RequestOptions,
  ): Promise<models.HostConfigResource> {
    return unwrapAsync(hostConfigGetApiV1ConfigHostId(
      this,
      request,
      options,
    ));
  }

  async putApiV1ConfigHostId(
    request: operations.PutApiV1ConfigHostIdRequest,
    options?: RequestOptions,
  ): Promise<models.HostConfigResource> {
    return unwrapAsync(hostConfigPutApiV1ConfigHostId(
      this,
      request,
      options,
    ));
  }

  async getApiV1ConfigHost(
    options?: RequestOptions,
  ): Promise<models.HostConfigResource> {
    return unwrapAsync(hostConfigGetApiV1ConfigHost(
      this,
      options,
    ));
  }
}
