/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indexerStatusGetApiV1Indexerstatus } from "../funcs/indexerStatusGetApiV1Indexerstatus.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class IndexerStatus extends ClientSDK {
  async getApiV1Indexerstatus(
    options?: RequestOptions,
  ): Promise<Array<models.IndexerStatusResource>> {
    return unwrapAsync(indexerStatusGetApiV1Indexerstatus(
      this,
      options,
    ));
  }
}
