/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { localizationGetApiV1Localization } from "../funcs/localizationGetApiV1Localization.js";
import { localizationGetApiV1LocalizationOptions } from "../funcs/localizationGetApiV1LocalizationOptions.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Localization extends ClientSDK {
  async getApiV1Localization(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(localizationGetApiV1Localization(
      this,
      options,
    ));
  }

  async getApiV1LocalizationOptions(
    options?: RequestOptions,
  ): Promise<Array<models.LocalizationOption>> {
    return unwrapAsync(localizationGetApiV1LocalizationOptions(
      this,
      options,
    ));
  }
}
