/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { logGetApiV1Log } from "../funcs/logGetApiV1Log.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Log extends ClientSDK {
  async getApiV1Log(
    request: operations.GetApiV1LogRequest,
    options?: RequestOptions,
  ): Promise<models.LogResourcePagingResource> {
    return unwrapAsync(logGetApiV1Log(
      this,
      request,
      options,
    ));
  }
}
