/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { newznabGetApiV1IndexerIdDownload } from "../funcs/newznabGetApiV1IndexerIdDownload.js";
import { newznabGetApiV1IndexerIdNewznab } from "../funcs/newznabGetApiV1IndexerIdNewznab.js";
import { newznabGetIdApi } from "../funcs/newznabGetIdApi.js";
import { newznabGetIdDownload } from "../funcs/newznabGetIdDownload.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Newznab extends ClientSDK {
  async getApiV1IndexerIdNewznab(
    request: operations.GetApiV1IndexerIdNewznabRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(newznabGetApiV1IndexerIdNewznab(
      this,
      request,
      options,
    ));
  }

  async getIdApi(
    request: operations.GetIdApiRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(newznabGetIdApi(
      this,
      request,
      options,
    ));
  }

  async getApiV1IndexerIdDownload(
    request: operations.GetApiV1IndexerIdDownloadRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(newznabGetApiV1IndexerIdDownload(
      this,
      request,
      options,
    ));
  }

  async getIdDownload(
    request: operations.GetIdDownloadRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(newznabGetIdDownload(
      this,
      request,
      options,
    ));
  }
}
