/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pingGetPing } from "../funcs/pingGetPing.js";
import { pingHeadPing } from "../funcs/pingHeadPing.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Ping extends ClientSDK {
  async getPing(
    options?: RequestOptions,
  ): Promise<models.PingResource> {
    return unwrapAsync(pingGetPing(
      this,
      options,
    ));
  }

  async headPing(
    options?: RequestOptions,
  ): Promise<models.PingResource> {
    return unwrapAsync(pingHeadPing(
      this,
      options,
    ));
  }
}
