/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { staticResourceGet } from "../funcs/staticResourceGet.js";
import { staticResourceGetContentPath } from "../funcs/staticResourceGetContentPath.js";
import { staticResourceGetLogin } from "../funcs/staticResourceGetLogin.js";
import { staticResourceGetPath } from "../funcs/staticResourceGetPath.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class StaticResource extends ClientSDK {
  async getLogin(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(staticResourceGetLogin(
      this,
      options,
    ));
  }

  async getContentPath(
    request: operations.GetContentPathRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(staticResourceGetContentPath(
      this,
      request,
      options,
    ));
  }

  async get(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(staticResourceGet(
      this,
      options,
    ));
  }

  async getPath(
    request: operations.GetPathRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(staticResourceGetPath(
      this,
      request,
      options,
    ));
  }
}
