/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { systemGetApiV1SystemRoutes } from "../funcs/systemGetApiV1SystemRoutes.js";
import { systemGetApiV1SystemRoutesDuplicate } from "../funcs/systemGetApiV1SystemRoutesDuplicate.js";
import { systemGetApiV1SystemStatus } from "../funcs/systemGetApiV1SystemStatus.js";
import { systemPostApiV1SystemRestart } from "../funcs/systemPostApiV1SystemRestart.js";
import { systemPostApiV1SystemShutdown } from "../funcs/systemPostApiV1SystemShutdown.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class System extends ClientSDK {
  async getApiV1SystemStatus(
    options?: RequestOptions,
  ): Promise<models.SystemResource> {
    return unwrapAsync(systemGetApiV1SystemStatus(
      this,
      options,
    ));
  }

  async getApiV1SystemRoutes(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(systemGetApiV1SystemRoutes(
      this,
      options,
    ));
  }

  async getApiV1SystemRoutesDuplicate(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(systemGetApiV1SystemRoutesDuplicate(
      this,
      options,
    ));
  }

  async postApiV1SystemShutdown(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(systemPostApiV1SystemShutdown(
      this,
      options,
    ));
  }

  async postApiV1SystemRestart(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(systemPostApiV1SystemRestart(
      this,
      options,
    ));
  }
}
