/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tagDetailsGetApiV1TagDetail } from "../funcs/tagDetailsGetApiV1TagDetail.js";
import { tagDetailsGetApiV1TagDetailId } from "../funcs/tagDetailsGetApiV1TagDetailId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class TagDetails extends ClientSDK {
  async getApiV1TagDetailId(
    request: operations.GetApiV1TagDetailIdRequest,
    options?: RequestOptions,
  ): Promise<models.TagDetailsResource> {
    return unwrapAsync(tagDetailsGetApiV1TagDetailId(
      this,
      request,
      options,
    ));
  }

  async getApiV1TagDetail(
    options?: RequestOptions,
  ): Promise<Array<models.TagDetailsResource>> {
    return unwrapAsync(tagDetailsGetApiV1TagDetail(
      this,
      options,
    ));
  }
}
