/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { uiConfigGetApiV1ConfigUi } from "../funcs/uiConfigGetApiV1ConfigUi.js";
import { uiConfigGetApiV1ConfigUiId } from "../funcs/uiConfigGetApiV1ConfigUiId.js";
import { uiConfigPutApiV1ConfigUiId } from "../funcs/uiConfigPutApiV1ConfigUiId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class UiConfig extends ClientSDK {
  async putApiV1ConfigUiId(
    request: operations.PutApiV1ConfigUiIdRequest,
    options?: RequestOptions,
  ): Promise<models.UiConfigResource> {
    return unwrapAsync(uiConfigPutApiV1ConfigUiId(
      this,
      request,
      options,
    ));
  }

  async getApiV1ConfigUiId(
    request: operations.GetApiV1ConfigUiIdRequest,
    options?: RequestOptions,
  ): Promise<models.UiConfigResource> {
    return unwrapAsync(uiConfigGetApiV1ConfigUiId(
      this,
      request,
      options,
    ));
  }

  async getApiV1ConfigUi(
    options?: RequestOptions,
  ): Promise<models.UiConfigResource> {
    return unwrapAsync(uiConfigGetApiV1ConfigUi(
      this,
      options,
    ));
  }
}
