/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { updateLogFileGetApiV1LogFileUpdate } from "../funcs/updateLogFileGetApiV1LogFileUpdate.js";
import { updateLogFileGetApiV1LogFileUpdateFilename } from "../funcs/updateLogFileGetApiV1LogFileUpdateFilename.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class UpdateLogFile extends ClientSDK {
  async getApiV1LogFileUpdate(
    options?: RequestOptions,
  ): Promise<Array<models.LogFileResource>> {
    return unwrapAsync(updateLogFileGetApiV1LogFileUpdate(
      this,
      options,
    ));
  }

  async getApiV1LogFileUpdateFilename(
    request: operations.GetApiV1LogFileUpdateFilenameRequest,
    options?: RequestOptions,
  ): Promise<string> {
    return unwrapAsync(updateLogFileGetApiV1LogFileUpdateFilename(
      this,
      request,
      options,
    ));
  }
}
