/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { updateGetApiV1Update } from "../funcs/updateGetApiV1Update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Update extends ClientSDK {
  async getApiV1Update(
    options?: RequestOptions,
  ): Promise<Array<models.UpdateResource>> {
    return unwrapAsync(updateGetApiV1Update(
      this,
      options,
    ));
  }
}
