/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the prowlarr SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx apiInfoGetApi.example.ts
 */

import { Prowlarr } from "prowlarr";

const prowlarr = new Prowlarr({
  security: {
    xApiKey: process.env["PROWLARR_X_API_KEY"] ?? "",
  },
});

async function main() {
  const result = await prowlarr.getApi();

  console.log(result);
}

main().catch(console.error);
