/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteApiV1AppprofileIdRequest = {
  id: number;
};

/** @internal */
export const DeleteApiV1AppprofileIdRequest$inboundSchema: z.ZodType<
  DeleteApiV1AppprofileIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type DeleteApiV1AppprofileIdRequest$Outbound = {
  id: number;
};

/** @internal */
export const DeleteApiV1AppprofileIdRequest$outboundSchema: z.ZodType<
  DeleteApiV1AppprofileIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteApiV1AppprofileIdRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiV1AppprofileIdRequest$ {
  /** @deprecated use `DeleteApiV1AppprofileIdRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteApiV1AppprofileIdRequest$inboundSchema;
  /** @deprecated use `DeleteApiV1AppprofileIdRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteApiV1AppprofileIdRequest$outboundSchema;
  /** @deprecated use `DeleteApiV1AppprofileIdRequest$Outbound` instead. */
  export type Outbound = DeleteApiV1AppprofileIdRequest$Outbound;
}

export function deleteApiV1AppprofileIdRequestToJSON(
  deleteApiV1AppprofileIdRequest: DeleteApiV1AppprofileIdRequest,
): string {
  return JSON.stringify(
    DeleteApiV1AppprofileIdRequest$outboundSchema.parse(
      deleteApiV1AppprofileIdRequest,
    ),
  );
}

export function deleteApiV1AppprofileIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiV1AppprofileIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteApiV1AppprofileIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiV1AppprofileIdRequest' from JSON`,
  );
}
