/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteApiV1CustomfilterIdRequest = {
  id: number;
};

/** @internal */
export const DeleteApiV1CustomfilterIdRequest$inboundSchema: z.ZodType<
  DeleteApiV1CustomfilterIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type DeleteApiV1CustomfilterIdRequest$Outbound = {
  id: number;
};

/** @internal */
export const DeleteApiV1CustomfilterIdRequest$outboundSchema: z.ZodType<
  DeleteApiV1CustomfilterIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteApiV1CustomfilterIdRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiV1CustomfilterIdRequest$ {
  /** @deprecated use `DeleteApiV1CustomfilterIdRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteApiV1CustomfilterIdRequest$inboundSchema;
  /** @deprecated use `DeleteApiV1CustomfilterIdRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteApiV1CustomfilterIdRequest$outboundSchema;
  /** @deprecated use `DeleteApiV1CustomfilterIdRequest$Outbound` instead. */
  export type Outbound = DeleteApiV1CustomfilterIdRequest$Outbound;
}

export function deleteApiV1CustomfilterIdRequestToJSON(
  deleteApiV1CustomfilterIdRequest: DeleteApiV1CustomfilterIdRequest,
): string {
  return JSON.stringify(
    DeleteApiV1CustomfilterIdRequest$outboundSchema.parse(
      deleteApiV1CustomfilterIdRequest,
    ),
  );
}

export function deleteApiV1CustomfilterIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiV1CustomfilterIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteApiV1CustomfilterIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiV1CustomfilterIdRequest' from JSON`,
  );
}
