/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteApiV1DownloadclientIdRequest = {
  id: number;
};

/** @internal */
export const DeleteApiV1DownloadclientIdRequest$inboundSchema: z.ZodType<
  DeleteApiV1DownloadclientIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type DeleteApiV1DownloadclientIdRequest$Outbound = {
  id: number;
};

/** @internal */
export const DeleteApiV1DownloadclientIdRequest$outboundSchema: z.ZodType<
  DeleteApiV1DownloadclientIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteApiV1DownloadclientIdRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiV1DownloadclientIdRequest$ {
  /** @deprecated use `DeleteApiV1DownloadclientIdRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteApiV1DownloadclientIdRequest$inboundSchema;
  /** @deprecated use `DeleteApiV1DownloadclientIdRequest$outboundSchema` instead. */
  export const outboundSchema =
    DeleteApiV1DownloadclientIdRequest$outboundSchema;
  /** @deprecated use `DeleteApiV1DownloadclientIdRequest$Outbound` instead. */
  export type Outbound = DeleteApiV1DownloadclientIdRequest$Outbound;
}

export function deleteApiV1DownloadclientIdRequestToJSON(
  deleteApiV1DownloadclientIdRequest: DeleteApiV1DownloadclientIdRequest,
): string {
  return JSON.stringify(
    DeleteApiV1DownloadclientIdRequest$outboundSchema.parse(
      deleteApiV1DownloadclientIdRequest,
    ),
  );
}

export function deleteApiV1DownloadclientIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiV1DownloadclientIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteApiV1DownloadclientIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiV1DownloadclientIdRequest' from JSON`,
  );
}
