/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteApiV1ApplicationsIdRequest = {
  id: number;
};

/** @internal */
export const DeleteApiV1ApplicationsIdRequest$inboundSchema: z.ZodType<
  DeleteApiV1ApplicationsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type DeleteApiV1ApplicationsIdRequest$Outbound = {
  id: number;
};

/** @internal */
export const DeleteApiV1ApplicationsIdRequest$outboundSchema: z.ZodType<
  DeleteApiV1ApplicationsIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteApiV1ApplicationsIdRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiV1ApplicationsIdRequest$ {
  /** @deprecated use `DeleteApiV1ApplicationsIdRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteApiV1ApplicationsIdRequest$inboundSchema;
  /** @deprecated use `DeleteApiV1ApplicationsIdRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteApiV1ApplicationsIdRequest$outboundSchema;
  /** @deprecated use `DeleteApiV1ApplicationsIdRequest$Outbound` instead. */
  export type Outbound = DeleteApiV1ApplicationsIdRequest$Outbound;
}

export function deleteApiV1ApplicationsIdRequestToJSON(
  deleteApiV1ApplicationsIdRequest: DeleteApiV1ApplicationsIdRequest,
): string {
  return JSON.stringify(
    DeleteApiV1ApplicationsIdRequest$outboundSchema.parse(
      deleteApiV1ApplicationsIdRequest,
    ),
  );
}

export function deleteApiV1ApplicationsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiV1ApplicationsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteApiV1ApplicationsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiV1ApplicationsIdRequest' from JSON`,
  );
}
