/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteApiV1TagIdRequest = {
  id: number;
};

/** @internal */
export const DeleteApiV1TagIdRequest$inboundSchema: z.ZodType<
  DeleteApiV1TagIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type DeleteApiV1TagIdRequest$Outbound = {
  id: number;
};

/** @internal */
export const DeleteApiV1TagIdRequest$outboundSchema: z.ZodType<
  DeleteApiV1TagIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteApiV1TagIdRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiV1TagIdRequest$ {
  /** @deprecated use `DeleteApiV1TagIdRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteApiV1TagIdRequest$inboundSchema;
  /** @deprecated use `DeleteApiV1TagIdRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteApiV1TagIdRequest$outboundSchema;
  /** @deprecated use `DeleteApiV1TagIdRequest$Outbound` instead. */
  export type Outbound = DeleteApiV1TagIdRequest$Outbound;
}

export function deleteApiV1TagIdRequestToJSON(
  deleteApiV1TagIdRequest: DeleteApiV1TagIdRequest,
): string {
  return JSON.stringify(
    DeleteApiV1TagIdRequest$outboundSchema.parse(deleteApiV1TagIdRequest),
  );
}

export function deleteApiV1TagIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiV1TagIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteApiV1TagIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiV1TagIdRequest' from JSON`,
  );
}
