/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1DownloadclientIdRequest = {
  id: number;
};

/** @internal */
export const GetApiV1DownloadclientIdRequest$inboundSchema: z.ZodType<
  GetApiV1DownloadclientIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type GetApiV1DownloadclientIdRequest$Outbound = {
  id: number;
};

/** @internal */
export const GetApiV1DownloadclientIdRequest$outboundSchema: z.ZodType<
  GetApiV1DownloadclientIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1DownloadclientIdRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiV1DownloadclientIdRequest$ {
  /** @deprecated use `GetApiV1DownloadclientIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiV1DownloadclientIdRequest$inboundSchema;
  /** @deprecated use `GetApiV1DownloadclientIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiV1DownloadclientIdRequest$outboundSchema;
  /** @deprecated use `GetApiV1DownloadclientIdRequest$Outbound` instead. */
  export type Outbound = GetApiV1DownloadclientIdRequest$Outbound;
}

export function getApiV1DownloadclientIdRequestToJSON(
  getApiV1DownloadclientIdRequest: GetApiV1DownloadclientIdRequest,
): string {
  return JSON.stringify(
    GetApiV1DownloadclientIdRequest$outboundSchema.parse(
      getApiV1DownloadclientIdRequest,
    ),
  );
}

export function getApiV1DownloadclientIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1DownloadclientIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1DownloadclientIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1DownloadclientIdRequest' from JSON`,
  );
}
