/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1FilesystemTypeRequest = {
  path?: string | undefined;
};

/** @internal */
export const GetApiV1FilesystemTypeRequest$inboundSchema: z.ZodType<
  GetApiV1FilesystemTypeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  path: z.string().optional(),
});

/** @internal */
export type GetApiV1FilesystemTypeRequest$Outbound = {
  path?: string | undefined;
};

/** @internal */
export const GetApiV1FilesystemTypeRequest$outboundSchema: z.ZodType<
  GetApiV1FilesystemTypeRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1FilesystemTypeRequest
> = z.object({
  path: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiV1FilesystemTypeRequest$ {
  /** @deprecated use `GetApiV1FilesystemTypeRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiV1FilesystemTypeRequest$inboundSchema;
  /** @deprecated use `GetApiV1FilesystemTypeRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiV1FilesystemTypeRequest$outboundSchema;
  /** @deprecated use `GetApiV1FilesystemTypeRequest$Outbound` instead. */
  export type Outbound = GetApiV1FilesystemTypeRequest$Outbound;
}

export function getApiV1FilesystemTypeRequestToJSON(
  getApiV1FilesystemTypeRequest: GetApiV1FilesystemTypeRequest,
): string {
  return JSON.stringify(
    GetApiV1FilesystemTypeRequest$outboundSchema.parse(
      getApiV1FilesystemTypeRequest,
    ),
  );
}

export function getApiV1FilesystemTypeRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1FilesystemTypeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1FilesystemTypeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1FilesystemTypeRequest' from JSON`,
  );
}
