/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1ApplicationsIdRequest = {
  id: number;
};

/** @internal */
export const GetApiV1ApplicationsIdRequest$inboundSchema: z.ZodType<
  GetApiV1ApplicationsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type GetApiV1ApplicationsIdRequest$Outbound = {
  id: number;
};

/** @internal */
export const GetApiV1ApplicationsIdRequest$outboundSchema: z.ZodType<
  GetApiV1ApplicationsIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1ApplicationsIdRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiV1ApplicationsIdRequest$ {
  /** @deprecated use `GetApiV1ApplicationsIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiV1ApplicationsIdRequest$inboundSchema;
  /** @deprecated use `GetApiV1ApplicationsIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiV1ApplicationsIdRequest$outboundSchema;
  /** @deprecated use `GetApiV1ApplicationsIdRequest$Outbound` instead. */
  export type Outbound = GetApiV1ApplicationsIdRequest$Outbound;
}

export function getApiV1ApplicationsIdRequestToJSON(
  getApiV1ApplicationsIdRequest: GetApiV1ApplicationsIdRequest,
): string {
  return JSON.stringify(
    GetApiV1ApplicationsIdRequest$outboundSchema.parse(
      getApiV1ApplicationsIdRequest,
    ),
  );
}

export function getApiV1ApplicationsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1ApplicationsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1ApplicationsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1ApplicationsIdRequest' from JSON`,
  );
}
