/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1ConfigDownloadclientIdRequest = {
  id: number;
};

/** @internal */
export const GetApiV1ConfigDownloadclientIdRequest$inboundSchema: z.ZodType<
  GetApiV1ConfigDownloadclientIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type GetApiV1ConfigDownloadclientIdRequest$Outbound = {
  id: number;
};

/** @internal */
export const GetApiV1ConfigDownloadclientIdRequest$outboundSchema: z.ZodType<
  GetApiV1ConfigDownloadclientIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1ConfigDownloadclientIdRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiV1ConfigDownloadclientIdRequest$ {
  /** @deprecated use `GetApiV1ConfigDownloadclientIdRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetApiV1ConfigDownloadclientIdRequest$inboundSchema;
  /** @deprecated use `GetApiV1ConfigDownloadclientIdRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetApiV1ConfigDownloadclientIdRequest$outboundSchema;
  /** @deprecated use `GetApiV1ConfigDownloadclientIdRequest$Outbound` instead. */
  export type Outbound = GetApiV1ConfigDownloadclientIdRequest$Outbound;
}

export function getApiV1ConfigDownloadclientIdRequestToJSON(
  getApiV1ConfigDownloadclientIdRequest: GetApiV1ConfigDownloadclientIdRequest,
): string {
  return JSON.stringify(
    GetApiV1ConfigDownloadclientIdRequest$outboundSchema.parse(
      getApiV1ConfigDownloadclientIdRequest,
    ),
  );
}

export function getApiV1ConfigDownloadclientIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1ConfigDownloadclientIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetApiV1ConfigDownloadclientIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1ConfigDownloadclientIdRequest' from JSON`,
  );
}
