/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1TagIdRequest = {
  id: number;
};

/** @internal */
export const GetApiV1TagIdRequest$inboundSchema: z.ZodType<
  GetApiV1TagIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type GetApiV1TagIdRequest$Outbound = {
  id: number;
};

/** @internal */
export const GetApiV1TagIdRequest$outboundSchema: z.ZodType<
  GetApiV1TagIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1TagIdRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiV1TagIdRequest$ {
  /** @deprecated use `GetApiV1TagIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiV1TagIdRequest$inboundSchema;
  /** @deprecated use `GetApiV1TagIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiV1TagIdRequest$outboundSchema;
  /** @deprecated use `GetApiV1TagIdRequest$Outbound` instead. */
  export type Outbound = GetApiV1TagIdRequest$Outbound;
}

export function getApiV1TagIdRequestToJSON(
  getApiV1TagIdRequest: GetApiV1TagIdRequest,
): string {
  return JSON.stringify(
    GetApiV1TagIdRequest$outboundSchema.parse(getApiV1TagIdRequest),
  );
}

export function getApiV1TagIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1TagIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1TagIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1TagIdRequest' from JSON`,
  );
}
