/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1LogFileFilenameRequest = {
  filename: string;
};

/** @internal */
export const GetApiV1LogFileFilenameRequest$inboundSchema: z.ZodType<
  GetApiV1LogFileFilenameRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  filename: z.string(),
});

/** @internal */
export type GetApiV1LogFileFilenameRequest$Outbound = {
  filename: string;
};

/** @internal */
export const GetApiV1LogFileFilenameRequest$outboundSchema: z.ZodType<
  GetApiV1LogFileFilenameRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1LogFileFilenameRequest
> = z.object({
  filename: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiV1LogFileFilenameRequest$ {
  /** @deprecated use `GetApiV1LogFileFilenameRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiV1LogFileFilenameRequest$inboundSchema;
  /** @deprecated use `GetApiV1LogFileFilenameRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiV1LogFileFilenameRequest$outboundSchema;
  /** @deprecated use `GetApiV1LogFileFilenameRequest$Outbound` instead. */
  export type Outbound = GetApiV1LogFileFilenameRequest$Outbound;
}

export function getApiV1LogFileFilenameRequestToJSON(
  getApiV1LogFileFilenameRequest: GetApiV1LogFileFilenameRequest,
): string {
  return JSON.stringify(
    GetApiV1LogFileFilenameRequest$outboundSchema.parse(
      getApiV1LogFileFilenameRequest,
    ),
  );
}

export function getApiV1LogFileFilenameRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1LogFileFilenameRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1LogFileFilenameRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1LogFileFilenameRequest' from JSON`,
  );
}
