/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1NotificationIdRequest = {
  id: number;
};

/** @internal */
export const GetApiV1NotificationIdRequest$inboundSchema: z.ZodType<
  GetApiV1NotificationIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type GetApiV1NotificationIdRequest$Outbound = {
  id: number;
};

/** @internal */
export const GetApiV1NotificationIdRequest$outboundSchema: z.ZodType<
  GetApiV1NotificationIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1NotificationIdRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiV1NotificationIdRequest$ {
  /** @deprecated use `GetApiV1NotificationIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiV1NotificationIdRequest$inboundSchema;
  /** @deprecated use `GetApiV1NotificationIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiV1NotificationIdRequest$outboundSchema;
  /** @deprecated use `GetApiV1NotificationIdRequest$Outbound` instead. */
  export type Outbound = GetApiV1NotificationIdRequest$Outbound;
}

export function getApiV1NotificationIdRequestToJSON(
  getApiV1NotificationIdRequest: GetApiV1NotificationIdRequest,
): string {
  return JSON.stringify(
    GetApiV1NotificationIdRequest$outboundSchema.parse(
      getApiV1NotificationIdRequest,
    ),
  );
}

export function getApiV1NotificationIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1NotificationIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1NotificationIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1NotificationIdRequest' from JSON`,
  );
}
