/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1CommandIdRequest = {
  id: number;
};

/** @internal */
export const GetApiV1CommandIdRequest$inboundSchema: z.ZodType<
  GetApiV1CommandIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type GetApiV1CommandIdRequest$Outbound = {
  id: number;
};

/** @internal */
export const GetApiV1CommandIdRequest$outboundSchema: z.ZodType<
  GetApiV1CommandIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1CommandIdRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiV1CommandIdRequest$ {
  /** @deprecated use `GetApiV1CommandIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiV1CommandIdRequest$inboundSchema;
  /** @deprecated use `GetApiV1CommandIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiV1CommandIdRequest$outboundSchema;
  /** @deprecated use `GetApiV1CommandIdRequest$Outbound` instead. */
  export type Outbound = GetApiV1CommandIdRequest$Outbound;
}

export function getApiV1CommandIdRequestToJSON(
  getApiV1CommandIdRequest: GetApiV1CommandIdRequest,
): string {
  return JSON.stringify(
    GetApiV1CommandIdRequest$outboundSchema.parse(getApiV1CommandIdRequest),
  );
}

export function getApiV1CommandIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1CommandIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1CommandIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1CommandIdRequest' from JSON`,
  );
}
