/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1CustomfilterIdRequest = {
  id: number;
};

/** @internal */
export const GetApiV1CustomfilterIdRequest$inboundSchema: z.ZodType<
  GetApiV1CustomfilterIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type GetApiV1CustomfilterIdRequest$Outbound = {
  id: number;
};

/** @internal */
export const GetApiV1CustomfilterIdRequest$outboundSchema: z.ZodType<
  GetApiV1CustomfilterIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1CustomfilterIdRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiV1CustomfilterIdRequest$ {
  /** @deprecated use `GetApiV1CustomfilterIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiV1CustomfilterIdRequest$inboundSchema;
  /** @deprecated use `GetApiV1CustomfilterIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiV1CustomfilterIdRequest$outboundSchema;
  /** @deprecated use `GetApiV1CustomfilterIdRequest$Outbound` instead. */
  export type Outbound = GetApiV1CustomfilterIdRequest$Outbound;
}

export function getApiV1CustomfilterIdRequestToJSON(
  getApiV1CustomfilterIdRequest: GetApiV1CustomfilterIdRequest,
): string {
  return JSON.stringify(
    GetApiV1CustomfilterIdRequest$outboundSchema.parse(
      getApiV1CustomfilterIdRequest,
    ),
  );
}

export function getApiV1CustomfilterIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1CustomfilterIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1CustomfilterIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1CustomfilterIdRequest' from JSON`,
  );
}
