/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1AppprofileIdRequest = {
  id: number;
};

/** @internal */
export const GetApiV1AppprofileIdRequest$inboundSchema: z.ZodType<
  GetApiV1AppprofileIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type GetApiV1AppprofileIdRequest$Outbound = {
  id: number;
};

/** @internal */
export const GetApiV1AppprofileIdRequest$outboundSchema: z.ZodType<
  GetApiV1AppprofileIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1AppprofileIdRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiV1AppprofileIdRequest$ {
  /** @deprecated use `GetApiV1AppprofileIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiV1AppprofileIdRequest$inboundSchema;
  /** @deprecated use `GetApiV1AppprofileIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiV1AppprofileIdRequest$outboundSchema;
  /** @deprecated use `GetApiV1AppprofileIdRequest$Outbound` instead. */
  export type Outbound = GetApiV1AppprofileIdRequest$Outbound;
}

export function getApiV1AppprofileIdRequestToJSON(
  getApiV1AppprofileIdRequest: GetApiV1AppprofileIdRequest,
): string {
  return JSON.stringify(
    GetApiV1AppprofileIdRequest$outboundSchema.parse(
      getApiV1AppprofileIdRequest,
    ),
  );
}

export function getApiV1AppprofileIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1AppprofileIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1AppprofileIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1AppprofileIdRequest' from JSON`,
  );
}
