/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetContentPathRequest = {
  path: string;
};

/** @internal */
export const GetContentPathRequest$inboundSchema: z.ZodType<
  GetContentPathRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  path: z.string(),
});

/** @internal */
export type GetContentPathRequest$Outbound = {
  path: string;
};

/** @internal */
export const GetContentPathRequest$outboundSchema: z.ZodType<
  GetContentPathRequest$Outbound,
  z.ZodTypeDef,
  GetContentPathRequest
> = z.object({
  path: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetContentPathRequest$ {
  /** @deprecated use `GetContentPathRequest$inboundSchema` instead. */
  export const inboundSchema = GetContentPathRequest$inboundSchema;
  /** @deprecated use `GetContentPathRequest$outboundSchema` instead. */
  export const outboundSchema = GetContentPathRequest$outboundSchema;
  /** @deprecated use `GetContentPathRequest$Outbound` instead. */
  export type Outbound = GetContentPathRequest$Outbound;
}

export function getContentPathRequestToJSON(
  getContentPathRequest: GetContentPathRequest,
): string {
  return JSON.stringify(
    GetContentPathRequest$outboundSchema.parse(getContentPathRequest),
  );
}

export function getContentPathRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetContentPathRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetContentPathRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetContentPathRequest' from JSON`,
  );
}
