/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetIdApiRequest = {
  id: number;
  t?: string | undefined;
  q?: string | undefined;
  cat?: string | undefined;
  imdbid?: string | undefined;
  tmdbid?: number | undefined;
  extended?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  minage?: number | undefined;
  maxage?: number | undefined;
  minsize?: number | undefined;
  maxsize?: number | undefined;
  rid?: number | undefined;
  tvmazeid?: number | undefined;
  traktid?: number | undefined;
  tvdbid?: number | undefined;
  doubanid?: number | undefined;
  season?: number | undefined;
  ep?: string | undefined;
  album?: string | undefined;
  artist?: string | undefined;
  label?: string | undefined;
  track?: string | undefined;
  year?: number | undefined;
  genre?: string | undefined;
  author?: string | undefined;
  title?: string | undefined;
  publisher?: string | undefined;
  configured?: string | undefined;
  source?: string | undefined;
  host?: string | undefined;
  server?: string | undefined;
};

/** @internal */
export const GetIdApiRequest$inboundSchema: z.ZodType<
  GetIdApiRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  t: z.string().optional(),
  q: z.string().optional(),
  cat: z.string().optional(),
  imdbid: z.string().optional(),
  tmdbid: z.number().int().optional(),
  extended: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  minage: z.number().int().optional(),
  maxage: z.number().int().optional(),
  minsize: z.number().int().optional(),
  maxsize: z.number().int().optional(),
  rid: z.number().int().optional(),
  tvmazeid: z.number().int().optional(),
  traktid: z.number().int().optional(),
  tvdbid: z.number().int().optional(),
  doubanid: z.number().int().optional(),
  season: z.number().int().optional(),
  ep: z.string().optional(),
  album: z.string().optional(),
  artist: z.string().optional(),
  label: z.string().optional(),
  track: z.string().optional(),
  year: z.number().int().optional(),
  genre: z.string().optional(),
  author: z.string().optional(),
  title: z.string().optional(),
  publisher: z.string().optional(),
  configured: z.string().optional(),
  source: z.string().optional(),
  host: z.string().optional(),
  server: z.string().optional(),
});

/** @internal */
export type GetIdApiRequest$Outbound = {
  id: number;
  t?: string | undefined;
  q?: string | undefined;
  cat?: string | undefined;
  imdbid?: string | undefined;
  tmdbid?: number | undefined;
  extended?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  minage?: number | undefined;
  maxage?: number | undefined;
  minsize?: number | undefined;
  maxsize?: number | undefined;
  rid?: number | undefined;
  tvmazeid?: number | undefined;
  traktid?: number | undefined;
  tvdbid?: number | undefined;
  doubanid?: number | undefined;
  season?: number | undefined;
  ep?: string | undefined;
  album?: string | undefined;
  artist?: string | undefined;
  label?: string | undefined;
  track?: string | undefined;
  year?: number | undefined;
  genre?: string | undefined;
  author?: string | undefined;
  title?: string | undefined;
  publisher?: string | undefined;
  configured?: string | undefined;
  source?: string | undefined;
  host?: string | undefined;
  server?: string | undefined;
};

/** @internal */
export const GetIdApiRequest$outboundSchema: z.ZodType<
  GetIdApiRequest$Outbound,
  z.ZodTypeDef,
  GetIdApiRequest
> = z.object({
  id: z.number().int(),
  t: z.string().optional(),
  q: z.string().optional(),
  cat: z.string().optional(),
  imdbid: z.string().optional(),
  tmdbid: z.number().int().optional(),
  extended: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  minage: z.number().int().optional(),
  maxage: z.number().int().optional(),
  minsize: z.number().int().optional(),
  maxsize: z.number().int().optional(),
  rid: z.number().int().optional(),
  tvmazeid: z.number().int().optional(),
  traktid: z.number().int().optional(),
  tvdbid: z.number().int().optional(),
  doubanid: z.number().int().optional(),
  season: z.number().int().optional(),
  ep: z.string().optional(),
  album: z.string().optional(),
  artist: z.string().optional(),
  label: z.string().optional(),
  track: z.string().optional(),
  year: z.number().int().optional(),
  genre: z.string().optional(),
  author: z.string().optional(),
  title: z.string().optional(),
  publisher: z.string().optional(),
  configured: z.string().optional(),
  source: z.string().optional(),
  host: z.string().optional(),
  server: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetIdApiRequest$ {
  /** @deprecated use `GetIdApiRequest$inboundSchema` instead. */
  export const inboundSchema = GetIdApiRequest$inboundSchema;
  /** @deprecated use `GetIdApiRequest$outboundSchema` instead. */
  export const outboundSchema = GetIdApiRequest$outboundSchema;
  /** @deprecated use `GetIdApiRequest$Outbound` instead. */
  export type Outbound = GetIdApiRequest$Outbound;
}

export function getIdApiRequestToJSON(
  getIdApiRequest: GetIdApiRequest,
): string {
  return JSON.stringify(GetIdApiRequest$outboundSchema.parse(getIdApiRequest));
}

export function getIdApiRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetIdApiRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetIdApiRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetIdApiRequest' from JSON`,
  );
}
