/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PostApiV1NotificationTestRequest = {
  forceTest?: boolean | undefined;
  notificationResource?: models.NotificationResource | undefined;
};

/** @internal */
export const PostApiV1NotificationTestRequest$inboundSchema: z.ZodType<
  PostApiV1NotificationTestRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  forceTest: z.boolean().default(false),
  NotificationResource: models.NotificationResource$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "NotificationResource": "notificationResource",
  });
});

/** @internal */
export type PostApiV1NotificationTestRequest$Outbound = {
  forceTest: boolean;
  NotificationResource?: models.NotificationResource$Outbound | undefined;
};

/** @internal */
export const PostApiV1NotificationTestRequest$outboundSchema: z.ZodType<
  PostApiV1NotificationTestRequest$Outbound,
  z.ZodTypeDef,
  PostApiV1NotificationTestRequest
> = z.object({
  forceTest: z.boolean().default(false),
  notificationResource: models.NotificationResource$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    notificationResource: "NotificationResource",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiV1NotificationTestRequest$ {
  /** @deprecated use `PostApiV1NotificationTestRequest$inboundSchema` instead. */
  export const inboundSchema = PostApiV1NotificationTestRequest$inboundSchema;
  /** @deprecated use `PostApiV1NotificationTestRequest$outboundSchema` instead. */
  export const outboundSchema = PostApiV1NotificationTestRequest$outboundSchema;
  /** @deprecated use `PostApiV1NotificationTestRequest$Outbound` instead. */
  export type Outbound = PostApiV1NotificationTestRequest$Outbound;
}

export function postApiV1NotificationTestRequestToJSON(
  postApiV1NotificationTestRequest: PostApiV1NotificationTestRequest,
): string {
  return JSON.stringify(
    PostApiV1NotificationTestRequest$outboundSchema.parse(
      postApiV1NotificationTestRequest,
    ),
  );
}

export function postApiV1NotificationTestRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1NotificationTestRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1NotificationTestRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1NotificationTestRequest' from JSON`,
  );
}
