/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PostApiV1NotificationRequest = {
  forceSave?: boolean | undefined;
  notificationResource?: models.NotificationResource | undefined;
};

/** @internal */
export const PostApiV1NotificationRequest$inboundSchema: z.ZodType<
  PostApiV1NotificationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  forceSave: z.boolean().default(false),
  NotificationResource: models.NotificationResource$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "NotificationResource": "notificationResource",
  });
});

/** @internal */
export type PostApiV1NotificationRequest$Outbound = {
  forceSave: boolean;
  NotificationResource?: models.NotificationResource$Outbound | undefined;
};

/** @internal */
export const PostApiV1NotificationRequest$outboundSchema: z.ZodType<
  PostApiV1NotificationRequest$Outbound,
  z.ZodTypeDef,
  PostApiV1NotificationRequest
> = z.object({
  forceSave: z.boolean().default(false),
  notificationResource: models.NotificationResource$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    notificationResource: "NotificationResource",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiV1NotificationRequest$ {
  /** @deprecated use `PostApiV1NotificationRequest$inboundSchema` instead. */
  export const inboundSchema = PostApiV1NotificationRequest$inboundSchema;
  /** @deprecated use `PostApiV1NotificationRequest$outboundSchema` instead. */
  export const outboundSchema = PostApiV1NotificationRequest$outboundSchema;
  /** @deprecated use `PostApiV1NotificationRequest$Outbound` instead. */
  export type Outbound = PostApiV1NotificationRequest$Outbound;
}

export function postApiV1NotificationRequestToJSON(
  postApiV1NotificationRequest: PostApiV1NotificationRequest,
): string {
  return JSON.stringify(
    PostApiV1NotificationRequest$outboundSchema.parse(
      postApiV1NotificationRequest,
    ),
  );
}

export function postApiV1NotificationRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1NotificationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1NotificationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1NotificationRequest' from JSON`,
  );
}
