/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PostApiV1ApplicationsActionNameRequest = {
  name: string;
  applicationResource?: models.ApplicationResource | undefined;
};

/** @internal */
export const PostApiV1ApplicationsActionNameRequest$inboundSchema: z.ZodType<
  PostApiV1ApplicationsActionNameRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  ApplicationResource: models.ApplicationResource$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "ApplicationResource": "applicationResource",
  });
});

/** @internal */
export type PostApiV1ApplicationsActionNameRequest$Outbound = {
  name: string;
  ApplicationResource?: models.ApplicationResource$Outbound | undefined;
};

/** @internal */
export const PostApiV1ApplicationsActionNameRequest$outboundSchema: z.ZodType<
  PostApiV1ApplicationsActionNameRequest$Outbound,
  z.ZodTypeDef,
  PostApiV1ApplicationsActionNameRequest
> = z.object({
  name: z.string(),
  applicationResource: models.ApplicationResource$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    applicationResource: "ApplicationResource",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiV1ApplicationsActionNameRequest$ {
  /** @deprecated use `PostApiV1ApplicationsActionNameRequest$inboundSchema` instead. */
  export const inboundSchema =
    PostApiV1ApplicationsActionNameRequest$inboundSchema;
  /** @deprecated use `PostApiV1ApplicationsActionNameRequest$outboundSchema` instead. */
  export const outboundSchema =
    PostApiV1ApplicationsActionNameRequest$outboundSchema;
  /** @deprecated use `PostApiV1ApplicationsActionNameRequest$Outbound` instead. */
  export type Outbound = PostApiV1ApplicationsActionNameRequest$Outbound;
}

export function postApiV1ApplicationsActionNameRequestToJSON(
  postApiV1ApplicationsActionNameRequest:
    PostApiV1ApplicationsActionNameRequest,
): string {
  return JSON.stringify(
    PostApiV1ApplicationsActionNameRequest$outboundSchema.parse(
      postApiV1ApplicationsActionNameRequest,
    ),
  );
}

export function postApiV1ApplicationsActionNameRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1ApplicationsActionNameRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiV1ApplicationsActionNameRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1ApplicationsActionNameRequest' from JSON`,
  );
}
