/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PutApiV1AppprofileIdRequest = {
  id: string;
  appProfileResource?: models.AppProfileResource | undefined;
};

/** @internal */
export const PutApiV1AppprofileIdRequest$inboundSchema: z.ZodType<
  PutApiV1AppprofileIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  AppProfileResource: models.AppProfileResource$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "AppProfileResource": "appProfileResource",
  });
});

/** @internal */
export type PutApiV1AppprofileIdRequest$Outbound = {
  id: string;
  AppProfileResource?: models.AppProfileResource$Outbound | undefined;
};

/** @internal */
export const PutApiV1AppprofileIdRequest$outboundSchema: z.ZodType<
  PutApiV1AppprofileIdRequest$Outbound,
  z.ZodTypeDef,
  PutApiV1AppprofileIdRequest
> = z.object({
  id: z.string(),
  appProfileResource: models.AppProfileResource$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    appProfileResource: "AppProfileResource",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutApiV1AppprofileIdRequest$ {
  /** @deprecated use `PutApiV1AppprofileIdRequest$inboundSchema` instead. */
  export const inboundSchema = PutApiV1AppprofileIdRequest$inboundSchema;
  /** @deprecated use `PutApiV1AppprofileIdRequest$outboundSchema` instead. */
  export const outboundSchema = PutApiV1AppprofileIdRequest$outboundSchema;
  /** @deprecated use `PutApiV1AppprofileIdRequest$Outbound` instead. */
  export type Outbound = PutApiV1AppprofileIdRequest$Outbound;
}

export function putApiV1AppprofileIdRequestToJSON(
  putApiV1AppprofileIdRequest: PutApiV1AppprofileIdRequest,
): string {
  return JSON.stringify(
    PutApiV1AppprofileIdRequest$outboundSchema.parse(
      putApiV1AppprofileIdRequest,
    ),
  );
}

export function putApiV1AppprofileIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<PutApiV1AppprofileIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutApiV1AppprofileIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutApiV1AppprofileIdRequest' from JSON`,
  );
}
