/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PutApiV1CustomfilterIdRequest = {
  id: string;
  customFilterResource?: models.CustomFilterResource | undefined;
};

/** @internal */
export const PutApiV1CustomfilterIdRequest$inboundSchema: z.ZodType<
  PutApiV1CustomfilterIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  CustomFilterResource: models.CustomFilterResource$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "CustomFilterResource": "customFilterResource",
  });
});

/** @internal */
export type PutApiV1CustomfilterIdRequest$Outbound = {
  id: string;
  CustomFilterResource?: models.CustomFilterResource$Outbound | undefined;
};

/** @internal */
export const PutApiV1CustomfilterIdRequest$outboundSchema: z.ZodType<
  PutApiV1CustomfilterIdRequest$Outbound,
  z.ZodTypeDef,
  PutApiV1CustomfilterIdRequest
> = z.object({
  id: z.string(),
  customFilterResource: models.CustomFilterResource$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    customFilterResource: "CustomFilterResource",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutApiV1CustomfilterIdRequest$ {
  /** @deprecated use `PutApiV1CustomfilterIdRequest$inboundSchema` instead. */
  export const inboundSchema = PutApiV1CustomfilterIdRequest$inboundSchema;
  /** @deprecated use `PutApiV1CustomfilterIdRequest$outboundSchema` instead. */
  export const outboundSchema = PutApiV1CustomfilterIdRequest$outboundSchema;
  /** @deprecated use `PutApiV1CustomfilterIdRequest$Outbound` instead. */
  export type Outbound = PutApiV1CustomfilterIdRequest$Outbound;
}

export function putApiV1CustomfilterIdRequestToJSON(
  putApiV1CustomfilterIdRequest: PutApiV1CustomfilterIdRequest,
): string {
  return JSON.stringify(
    PutApiV1CustomfilterIdRequest$outboundSchema.parse(
      putApiV1CustomfilterIdRequest,
    ),
  );
}

export function putApiV1CustomfilterIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<PutApiV1CustomfilterIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutApiV1CustomfilterIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutApiV1CustomfilterIdRequest' from JSON`,
  );
}
