/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ApplicationSyncLevel = {
  Disabled: "disabled",
  AddOnly: "addOnly",
  FullSync: "fullSync",
} as const;
export type ApplicationSyncLevel = ClosedEnum<typeof ApplicationSyncLevel>;

/** @internal */
export const ApplicationSyncLevel$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationSyncLevel
> = z.nativeEnum(ApplicationSyncLevel);

/** @internal */
export const ApplicationSyncLevel$outboundSchema: z.ZodNativeEnum<
  typeof ApplicationSyncLevel
> = ApplicationSyncLevel$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationSyncLevel$ {
  /** @deprecated use `ApplicationSyncLevel$inboundSchema` instead. */
  export const inboundSchema = ApplicationSyncLevel$inboundSchema;
  /** @deprecated use `ApplicationSyncLevel$outboundSchema` instead. */
  export const outboundSchema = ApplicationSyncLevel$outboundSchema;
}
