/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const AuthenticationType = {
  None: "none",
  Basic: "basic",
  Forms: "forms",
  External: "external",
} as const;
export type AuthenticationType = ClosedEnum<typeof AuthenticationType>;

/** @internal */
export const AuthenticationType$inboundSchema: z.ZodNativeEnum<
  typeof AuthenticationType
> = z.nativeEnum(AuthenticationType);

/** @internal */
export const AuthenticationType$outboundSchema: z.ZodNativeEnum<
  typeof AuthenticationType
> = AuthenticationType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthenticationType$ {
  /** @deprecated use `AuthenticationType$inboundSchema` instead. */
  export const inboundSchema = AuthenticationType$inboundSchema;
  /** @deprecated use `AuthenticationType$outboundSchema` instead. */
  export const outboundSchema = AuthenticationType$outboundSchema;
}
