/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CommandStatus = {
  Queued: "queued",
  Started: "started",
  Completed: "completed",
  Failed: "failed",
  Aborted: "aborted",
  Cancelled: "cancelled",
  Orphaned: "orphaned",
} as const;
export type CommandStatus = ClosedEnum<typeof CommandStatus>;

/** @internal */
export const CommandStatus$inboundSchema: z.ZodNativeEnum<
  typeof CommandStatus
> = z.nativeEnum(CommandStatus);

/** @internal */
export const CommandStatus$outboundSchema: z.ZodNativeEnum<
  typeof CommandStatus
> = CommandStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CommandStatus$ {
  /** @deprecated use `CommandStatus$inboundSchema` instead. */
  export const inboundSchema = CommandStatus$inboundSchema;
  /** @deprecated use `CommandStatus$outboundSchema` instead. */
  export const outboundSchema = CommandStatus$outboundSchema;
}
