/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const DownloadProtocol = {
  Unknown: "unknown",
  Usenet: "usenet",
  Torrent: "torrent",
} as const;
export type DownloadProtocol = ClosedEnum<typeof DownloadProtocol>;

/** @internal */
export const DownloadProtocol$inboundSchema: z.ZodNativeEnum<
  typeof DownloadProtocol
> = z.nativeEnum(DownloadProtocol);

/** @internal */
export const DownloadProtocol$outboundSchema: z.ZodNativeEnum<
  typeof DownloadProtocol
> = DownloadProtocol$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DownloadProtocol$ {
  /** @deprecated use `DownloadProtocol$inboundSchema` instead. */
  export const inboundSchema = DownloadProtocol$inboundSchema;
  /** @deprecated use `DownloadProtocol$outboundSchema` instead. */
  export const outboundSchema = DownloadProtocol$outboundSchema;
}
