/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const HealthCheckResult = {
  Ok: "ok",
  Notice: "notice",
  Warning: "warning",
  Error: "error",
} as const;
export type HealthCheckResult = ClosedEnum<typeof HealthCheckResult>;

/** @internal */
export const HealthCheckResult$inboundSchema: z.ZodNativeEnum<
  typeof HealthCheckResult
> = z.nativeEnum(HealthCheckResult);

/** @internal */
export const HealthCheckResult$outboundSchema: z.ZodNativeEnum<
  typeof HealthCheckResult
> = HealthCheckResult$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace HealthCheckResult$ {
  /** @deprecated use `HealthCheckResult$inboundSchema` instead. */
  export const inboundSchema = HealthCheckResult$inboundSchema;
  /** @deprecated use `HealthCheckResult$outboundSchema` instead. */
  export const outboundSchema = HealthCheckResult$outboundSchema;
}
