/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const HistoryEventType = {
  Unknown: "unknown",
  ReleaseGrabbed: "releaseGrabbed",
  IndexerQuery: "indexerQuery",
  IndexerRss: "indexerRss",
  IndexerAuth: "indexerAuth",
  IndexerInfo: "indexerInfo",
} as const;
export type HistoryEventType = ClosedEnum<typeof HistoryEventType>;

/** @internal */
export const HistoryEventType$inboundSchema: z.ZodNativeEnum<
  typeof HistoryEventType
> = z.nativeEnum(HistoryEventType);

/** @internal */
export const HistoryEventType$outboundSchema: z.ZodNativeEnum<
  typeof HistoryEventType
> = HistoryEventType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace HistoryEventType$ {
  /** @deprecated use `HistoryEventType$inboundSchema` instead. */
  export const inboundSchema = HistoryEventType$inboundSchema;
  /** @deprecated use `HistoryEventType$outboundSchema` instead. */
  export const outboundSchema = HistoryEventType$outboundSchema;
}
