/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const IndexerPrivacy = {
  Public: "public",
  SemiPrivate: "semiPrivate",
  Private: "private",
} as const;
export type IndexerPrivacy = ClosedEnum<typeof IndexerPrivacy>;

/** @internal */
export const IndexerPrivacy$inboundSchema: z.ZodNativeEnum<
  typeof IndexerPrivacy
> = z.nativeEnum(IndexerPrivacy);

/** @internal */
export const IndexerPrivacy$outboundSchema: z.ZodNativeEnum<
  typeof IndexerPrivacy
> = IndexerPrivacy$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IndexerPrivacy$ {
  /** @deprecated use `IndexerPrivacy$inboundSchema` instead. */
  export const inboundSchema = IndexerPrivacy$inboundSchema;
  /** @deprecated use `IndexerPrivacy$outboundSchema` instead. */
  export const outboundSchema = IndexerPrivacy$outboundSchema;
}
