/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const PrivacyLevel = {
  Normal: "normal",
  Password: "password",
  ApiKey: "apiKey",
  UserName: "userName",
} as const;
export type PrivacyLevel = ClosedEnum<typeof PrivacyLevel>;

/** @internal */
export const PrivacyLevel$inboundSchema: z.ZodNativeEnum<typeof PrivacyLevel> =
  z.nativeEnum(PrivacyLevel);

/** @internal */
export const PrivacyLevel$outboundSchema: z.ZodNativeEnum<typeof PrivacyLevel> =
  PrivacyLevel$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PrivacyLevel$ {
  /** @deprecated use `PrivacyLevel$inboundSchema` instead. */
  export const inboundSchema = PrivacyLevel$inboundSchema;
  /** @deprecated use `PrivacyLevel$outboundSchema` instead. */
  export const outboundSchema = PrivacyLevel$outboundSchema;
}
