/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ProviderMessageType = {
  Info: "info",
  Warning: "warning",
  Error: "error",
} as const;
export type ProviderMessageType = ClosedEnum<typeof ProviderMessageType>;

/** @internal */
export const ProviderMessageType$inboundSchema: z.ZodNativeEnum<
  typeof ProviderMessageType
> = z.nativeEnum(ProviderMessageType);

/** @internal */
export const ProviderMessageType$outboundSchema: z.ZodNativeEnum<
  typeof ProviderMessageType
> = ProviderMessageType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProviderMessageType$ {
  /** @deprecated use `ProviderMessageType$inboundSchema` instead. */
  export const inboundSchema = ProviderMessageType$inboundSchema;
  /** @deprecated use `ProviderMessageType$outboundSchema` instead. */
  export const outboundSchema = ProviderMessageType$outboundSchema;
}
