/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ProxyType = {
  Http: "http",
  Socks4: "socks4",
  Socks5: "socks5",
} as const;
export type ProxyType = ClosedEnum<typeof ProxyType>;

/** @internal */
export const ProxyType$inboundSchema: z.ZodNativeEnum<typeof ProxyType> = z
  .nativeEnum(ProxyType);

/** @internal */
export const ProxyType$outboundSchema: z.ZodNativeEnum<typeof ProxyType> =
  ProxyType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProxyType$ {
  /** @deprecated use `ProxyType$inboundSchema` instead. */
  export const inboundSchema = ProxyType$inboundSchema;
  /** @deprecated use `ProxyType$outboundSchema` instead. */
  export const outboundSchema = ProxyType$outboundSchema;
}
