/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  DownloadProtocol,
  DownloadProtocol$inboundSchema,
  DownloadProtocol$outboundSchema,
} from "./downloadprotocol.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  IndexerCategoryInput,
  IndexerCategoryInput$inboundSchema,
  IndexerCategoryInput$Outbound,
  IndexerCategoryInput$outboundSchema,
} from "./indexercategoryinput.js";

export type ReleaseResourceInput = {
  id?: number | undefined;
  guid?: string | null | undefined;
  age?: number | undefined;
  ageHours?: number | undefined;
  ageMinutes?: number | undefined;
  size?: number | undefined;
  files?: number | null | undefined;
  grabs?: number | null | undefined;
  indexerId?: number | undefined;
  indexer?: string | null | undefined;
  subGroup?: string | null | undefined;
  releaseHash?: string | null | undefined;
  title?: string | null | undefined;
  sortTitle?: string | null | undefined;
  imdbId?: number | undefined;
  tmdbId?: number | undefined;
  tvdbId?: number | undefined;
  tvMazeId?: number | undefined;
  publishDate?: Date | undefined;
  commentUrl?: string | null | undefined;
  downloadUrl?: string | null | undefined;
  infoUrl?: string | null | undefined;
  posterUrl?: string | null | undefined;
  indexerFlags?: Array<string> | null | undefined;
  categories?: Array<IndexerCategoryInput> | null | undefined;
  magnetUrl?: string | null | undefined;
  infoHash?: string | null | undefined;
  seeders?: number | null | undefined;
  leechers?: number | null | undefined;
  protocol?: DownloadProtocol | undefined;
  downloadClientId?: number | null | undefined;
};

/** @internal */
export const ReleaseResourceInput$inboundSchema: z.ZodType<
  ReleaseResourceInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  guid: z.nullable(z.string()).optional(),
  age: z.number().int().optional(),
  ageHours: z.number().optional(),
  ageMinutes: z.number().optional(),
  size: z.number().int().optional(),
  files: z.nullable(z.number().int()).optional(),
  grabs: z.nullable(z.number().int()).optional(),
  indexerId: z.number().int().optional(),
  indexer: z.nullable(z.string()).optional(),
  subGroup: z.nullable(z.string()).optional(),
  releaseHash: z.nullable(z.string()).optional(),
  title: z.nullable(z.string()).optional(),
  sortTitle: z.nullable(z.string()).optional(),
  imdbId: z.number().int().optional(),
  tmdbId: z.number().int().optional(),
  tvdbId: z.number().int().optional(),
  tvMazeId: z.number().int().optional(),
  publishDate: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  commentUrl: z.nullable(z.string()).optional(),
  downloadUrl: z.nullable(z.string()).optional(),
  infoUrl: z.nullable(z.string()).optional(),
  posterUrl: z.nullable(z.string()).optional(),
  indexerFlags: z.nullable(z.array(z.string())).optional(),
  categories: z.nullable(z.array(IndexerCategoryInput$inboundSchema))
    .optional(),
  magnetUrl: z.nullable(z.string()).optional(),
  infoHash: z.nullable(z.string()).optional(),
  seeders: z.nullable(z.number().int()).optional(),
  leechers: z.nullable(z.number().int()).optional(),
  protocol: DownloadProtocol$inboundSchema.optional(),
  downloadClientId: z.nullable(z.number().int()).optional(),
});

/** @internal */
export type ReleaseResourceInput$Outbound = {
  id?: number | undefined;
  guid?: string | null | undefined;
  age?: number | undefined;
  ageHours?: number | undefined;
  ageMinutes?: number | undefined;
  size?: number | undefined;
  files?: number | null | undefined;
  grabs?: number | null | undefined;
  indexerId?: number | undefined;
  indexer?: string | null | undefined;
  subGroup?: string | null | undefined;
  releaseHash?: string | null | undefined;
  title?: string | null | undefined;
  sortTitle?: string | null | undefined;
  imdbId?: number | undefined;
  tmdbId?: number | undefined;
  tvdbId?: number | undefined;
  tvMazeId?: number | undefined;
  publishDate?: string | undefined;
  commentUrl?: string | null | undefined;
  downloadUrl?: string | null | undefined;
  infoUrl?: string | null | undefined;
  posterUrl?: string | null | undefined;
  indexerFlags?: Array<string> | null | undefined;
  categories?: Array<IndexerCategoryInput$Outbound> | null | undefined;
  magnetUrl?: string | null | undefined;
  infoHash?: string | null | undefined;
  seeders?: number | null | undefined;
  leechers?: number | null | undefined;
  protocol?: string | undefined;
  downloadClientId?: number | null | undefined;
};

/** @internal */
export const ReleaseResourceInput$outboundSchema: z.ZodType<
  ReleaseResourceInput$Outbound,
  z.ZodTypeDef,
  ReleaseResourceInput
> = z.object({
  id: z.number().int().optional(),
  guid: z.nullable(z.string()).optional(),
  age: z.number().int().optional(),
  ageHours: z.number().optional(),
  ageMinutes: z.number().optional(),
  size: z.number().int().optional(),
  files: z.nullable(z.number().int()).optional(),
  grabs: z.nullable(z.number().int()).optional(),
  indexerId: z.number().int().optional(),
  indexer: z.nullable(z.string()).optional(),
  subGroup: z.nullable(z.string()).optional(),
  releaseHash: z.nullable(z.string()).optional(),
  title: z.nullable(z.string()).optional(),
  sortTitle: z.nullable(z.string()).optional(),
  imdbId: z.number().int().optional(),
  tmdbId: z.number().int().optional(),
  tvdbId: z.number().int().optional(),
  tvMazeId: z.number().int().optional(),
  publishDate: z.date().transform(v => v.toISOString()).optional(),
  commentUrl: z.nullable(z.string()).optional(),
  downloadUrl: z.nullable(z.string()).optional(),
  infoUrl: z.nullable(z.string()).optional(),
  posterUrl: z.nullable(z.string()).optional(),
  indexerFlags: z.nullable(z.array(z.string())).optional(),
  categories: z.nullable(z.array(IndexerCategoryInput$outboundSchema))
    .optional(),
  magnetUrl: z.nullable(z.string()).optional(),
  infoHash: z.nullable(z.string()).optional(),
  seeders: z.nullable(z.number().int()).optional(),
  leechers: z.nullable(z.number().int()).optional(),
  protocol: DownloadProtocol$outboundSchema.optional(),
  downloadClientId: z.nullable(z.number().int()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReleaseResourceInput$ {
  /** @deprecated use `ReleaseResourceInput$inboundSchema` instead. */
  export const inboundSchema = ReleaseResourceInput$inboundSchema;
  /** @deprecated use `ReleaseResourceInput$outboundSchema` instead. */
  export const outboundSchema = ReleaseResourceInput$outboundSchema;
  /** @deprecated use `ReleaseResourceInput$Outbound` instead. */
  export type Outbound = ReleaseResourceInput$Outbound;
}

export function releaseResourceInputToJSON(
  releaseResourceInput: ReleaseResourceInput,
): string {
  return JSON.stringify(
    ReleaseResourceInput$outboundSchema.parse(releaseResourceInput),
  );
}

export function releaseResourceInputFromJSON(
  jsonString: string,
): SafeParseResult<ReleaseResourceInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReleaseResourceInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReleaseResourceInput' from JSON`,
  );
}
