/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const RuntimeMode = {
  Console: "console",
  Service: "service",
  Tray: "tray",
} as const;
export type RuntimeMode = ClosedEnum<typeof RuntimeMode>;

/** @internal */
export const RuntimeMode$inboundSchema: z.ZodNativeEnum<typeof RuntimeMode> = z
  .nativeEnum(RuntimeMode);

/** @internal */
export const RuntimeMode$outboundSchema: z.ZodNativeEnum<typeof RuntimeMode> =
  RuntimeMode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RuntimeMode$ {
  /** @deprecated use `RuntimeMode$inboundSchema` instead. */
  export const inboundSchema = RuntimeMode$inboundSchema;
  /** @deprecated use `RuntimeMode$outboundSchema` instead. */
  export const outboundSchema = RuntimeMode$outboundSchema;
}
