/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const UpdateMechanism = {
  BuiltIn: "builtIn",
  Script: "script",
  External: "external",
  Apt: "apt",
  Docker: "docker",
} as const;
export type UpdateMechanism = ClosedEnum<typeof UpdateMechanism>;

/** @internal */
export const UpdateMechanism$inboundSchema: z.ZodNativeEnum<
  typeof UpdateMechanism
> = z.nativeEnum(UpdateMechanism);

/** @internal */
export const UpdateMechanism$outboundSchema: z.ZodNativeEnum<
  typeof UpdateMechanism
> = UpdateMechanism$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateMechanism$ {
  /** @deprecated use `UpdateMechanism$inboundSchema` instead. */
  export const inboundSchema = UpdateMechanism$inboundSchema;
  /** @deprecated use `UpdateMechanism$outboundSchema` instead. */
  export const outboundSchema = UpdateMechanism$outboundSchema;
}
